In [1]:
import pandas as pd

In [2]:
file_path = r"C:\Users\Asus\Desktop\Projects\Dataset\student_performance_dataset.csv"

df = pd.read_csv(file_path)

df.sample(10)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
778,779,Female,5.0,100.0,5.4,NaN,Yes,Yes,No,57.4,87.1,B
459,460,Male,4.2,74.7,5.5,Masters,Yes,Yes,No,69.3,86.8,B
95,96,Female,2.1,81.3,8.9,Bachelors,Yes,No,No,45.4,74.8,C
485,486,Female,2.3,82.9,7.4,Masters,Yes,Yes,Yes,74.9,87.3,B
729,730,Female,4.0,79.9,7.1,PhD,Yes,No,No,99.4,98.9,A
539,540,Female,1.2,75.8,7.1,Bachelors,Yes,Yes,Yes,45.0,57.3,F
966,967,Male,4.3,91.8,7.3,High School,Yes,Yes,Yes,63.8,90.0,A
854,855,Male,2.9,86.1,6.8,Bachelors,Yes,No,No,67.0,81.9,B
929,930,Male,1.5,89.2,7.3,High School,Yes,No,No,53.8,80.8,B
510,511,Male,3.2,82.4,4.3,High School,Yes,Yes,Yes,79.2,79.9,C

In [3]:
df.isna().sum()

student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

In [4]:
df.duplicated().value_counts()

False    1000
Name: count, dtype: int64

In [5]:
df['parental_education'] = df['parental_education'].ffill()

In [6]:
df.sample(10)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
494,495,Male,7.3,94.6,4.1,Bachelors,Yes,No,No,83.6,88.5,B
466,467,Female,2.5,73.1,5.5,High School,Yes,No,Yes,79.2,77.1,C
694,695,Female,3.0,85.0,8.2,Bachelors,Yes,No,No,69.9,89.6,B
486,487,Male,1.4,81.9,4.3,High School,Yes,No,No,69.6,66.6,D
778,779,Female,5.0,100.0,5.4,High School,Yes,Yes,No,57.4,87.1,B
958,959,Female,4.9,63.5,5.6,Bachelors,Yes,Yes,No,73.0,87.6,B
499,500,Female,6.3,87.8,6.2,High School,Yes,No,No,73.9,99.6,A
380,381,Female,3.4,100.0,6.8,Bachelors,No,Yes,No,44.7,77.4,C
335,336,Female,0.9,82.4,6.2,Masters,Yes,Yes,No,82.4,71.2,C
309,310,Female,3.0,100.0,8.5,High School,Yes,No,Yes,66.9,83.3,B

In [7]:
df['parental_education'].value_counts()

parental_education
High School    400
Bachelors      335
Masters        211
PhD             54
Name: count, dtype: int64

In [8]:
df.dtypes

student_id                      int64
gender                            str
study_time_hours              float64
attendance_percent            float64
sleep_hours                   float64
parental_education                str
internet_access                   str
extracurricular_activities        str
part_time_job                     str
previous_grade                float64
final_exam_score              float64
final_grade                       str
dtype: object

In [9]:
df.columns

Index(['student_id', 'gender', 'study_time_hours', 'attendance_percent',
       'sleep_hours', 'parental_education', 'internet_access',
       'extracurricular_activities', 'part_time_job', 'previous_grade',
       'final_exam_score', 'final_grade'],
      dtype='str')

In [10]:
df.sample(5)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
794,795,Male,3.8,83.1,8.0,High School,Yes,No,No,75.7,89.5,B
349,350,Male,4.2,68.8,6.2,Masters,Yes,Yes,Yes,50.5,74.0,C
245,246,Female,5.8,76.5,7.4,Bachelors,Yes,Yes,No,79.9,100.0,A
241,242,Male,3.3,97.8,7.6,High School,Yes,No,Yes,70.4,85.1,B
516,517,Female,3.5,96.7,6.1,High School,Yes,No,No,70.1,84.2,B

In [11]:
mappings = {'Yes':True,'No':False}
df['internet_access'] = df['internet_access'].map(mappings)
df['extracurricular_activities'] = df['extracurricular_activities'].map(mappings)
df['part_time_job'] = df['part_time_job'].map(mappings)

In [12]:
df.sample(10)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
19,20,Male,4.4,77.4,8.4,Masters,False,False,True,77.0,92.8,A
3,4,Male,2.6,77.5,8.0,Bachelors,True,True,False,85.1,83.8,B
786,787,Male,3.7,81.8,5.2,Bachelors,True,False,False,58.9,77.0,C
545,546,Female,6.3,90.0,6.3,High School,True,True,False,85.1,100.0,A
145,146,Male,1.0,67.3,5.7,High School,True,False,False,79.3,65.2,D
391,392,Male,3.1,84.6,6.5,High School,True,True,False,62.4,87.3,B
358,359,Male,4.3,75.7,3.8,PhD,True,False,False,62.4,81.9,B
171,172,Male,2.9,77.0,6.8,Bachelors,True,False,False,68.2,71.8,C
668,669,Male,2.7,71.5,8.9,High School,True,False,True,91.3,97.6,A
600,601,Male,5.8,92.3,6.7,High School,True,True,True,69.1,93.4,A

In [13]:
# df.to_csv('Dataset/cleaned_student_data.csv',index=False)

In [14]:
df['parental_education'].value_counts()

parental_education
High School    400
Bachelors      335
Masters        211
PhD             54
Name: count, dtype: int64

In [15]:
df['final_grade'].value_counts()

final_grade
B    354
A    284
C    261
D     89
F     12
Name: count, dtype: int64