In [1]:
import pandas as pd

In [2]:
file_path = r"C:\Users\Asus\Desktop\Projects\Dataset\Student_data.csv"

df = pd.read_csv(file_path)

df.sample(10)

,Student_ID,Gender,Age,Major,Attendance_Pct,Study_Hours_Per_Day,Previous_CGPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
1612,ID01613,Male,18,Business,70.2,5.2,3.63,7.5,5,3.70
1220,ID01221,Female,24,Psychology,98.3,5.0,3.52,8.0,6,3.98
4572,ID04573,Male,24,Business,83.1,2.8,3.14,5.5,3,3.36
2766,ID02767,Male,24,Psychology,65.8,5.3,2.14,7.7,5,2.25
556,ID00557,Male,18,Business,77.0,6.5,2.80,8.4,2,2.87
439,ID00440,Male,19,Computer Science,86.6,3.9,3.21,6.8,7,3.38
932,ID00933,Female,23,Computer Science,80.5,4.2,3.21,6.1,13,3.49
4732,ID04733,Female,21,Psychology,86.6,3.2,3.58,6.9,9,3.97
3948,ID03949,Male,19,Economics,91.7,4.2,3.57,7.5,13,3.99
1304,ID01305,Female,19,Psychology,67.5,2.3,2.44,7.5,7,2.42

In [3]:
df.isna().sum()

Student_ID             0
Gender                 0
Age                    0
Major                  0
Attendance_Pct         0
Study_Hours_Per_Day    0
Previous_CGPA          0
Sleep_Hours            0
Social_Hours_Week      0
Final_CGPA             0
dtype: int64

In [4]:
df.duplicated().value_counts()

False    5000
Name: count, dtype: int64

In [5]:
df.sample(10)

,Student_ID,Gender,Age,Major,Attendance_Pct,Study_Hours_Per_Day,Previous_CGPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
194,ID00195,Male,21,Mathematics,85.5,4.5,3.84,7.1,5,4.00
2318,ID02319,Male,21,Economics,100.0,4.8,3.43,5.7,6,3.78
267,ID00268,Female,21,Mathematics,91.3,7.3,3.50,5.3,12,3.94
506,ID00507,Female,18,Engineering,94.1,7.2,2.61,7.5,11,2.94
1497,ID01498,Male,23,Mathematics,68.1,4.6,2.64,8.5,11,2.47
366,ID00367,Female,24,Engineering,88.7,3.6,2.44,5.8,3,2.67
4696,ID04697,Male,20,Mathematics,69.9,1.5,3.08,8.7,8,2.73
50,ID00051,Female,18,Economics,71.0,2.4,2.31,7.3,6,2.20
2362,ID02363,Male,21,Economics,100.0,2.6,2.37,5.4,13,2.66
2092,ID02093,Male,23,Engineering,88.7,0.6,2.93,6.0,11,3.08

In [6]:
df.dtypes

Student_ID                 str
Gender                     str
Age                      int64
Major                      str
Attendance_Pct         float64
Study_Hours_Per_Day    float64
Previous_CGPA          float64
Sleep_Hours            float64
Social_Hours_Week        int64
Final_CGPA             float64
dtype: object

In [7]:
df.columns

Index(['Student_ID', 'Gender', 'Age', 'Major', 'Attendance_Pct',
       'Study_Hours_Per_Day', 'Previous_CGPA', 'Sleep_Hours',
       'Social_Hours_Week', 'Final_CGPA'],
      dtype='str')

In [8]:
df.sample(5)

,Student_ID,Gender,Age,Major,Attendance_Pct,Study_Hours_Per_Day,Previous_CGPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
2092,ID02093,Male,23,Engineering,88.7,0.6,2.93,6.0,11,3.08
270,ID00271,Female,24,Psychology,100.0,5.3,3.42,5.5,5,3.56
1498,ID01499,Male,21,Computer Science,78.2,1.5,3.77,8.0,9,3.87
2876,ID02877,Male,19,Business,72.3,5.3,2.51,8.1,2,2.56
526,ID00527,Male,21,Computer Science,99.6,2.5,3.26,8.4,8,3.37

In [9]:
df.to_csv('Dataset/cleaned_student_data.csv',index=False)